export const EMAIL_REQUIRED = 'Email is required.';
export const INVALID_EMAIL = 'The email address you input is invalid.';
export const PASSWORD_REQUIRED = 'Password is required.';
export const PASSWORD_MIN_LENGTH = 6;
export const PASSWORD_TOO_SHORT = `Passowrd should be at least ${PASSWORD_MIN_LENGTH} characters`;
export const USERNAME_REQUIRED = 'Username is required.';
export const INVALID_USERNAME = 'Username contains invalid characters.';
export const USERNAME_MAX_LENGTH = 20;
export const USERNAME_TOO_LONG = `Username cannot exceed ${USERNAME_MAX_LENGTH} characters`;
export const USERNAME_OR_EMAIL_REQUIRED = 'Username or email is required.'
export const apiBaseUrl = import.meta.env.VITE_API_BASE_URL + '/api';